/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/three.js/demo-1': RouteRecordInfo<'/three.js/demo-1', '/three/js/demo-1', Record<never, never>, Record<never, never>>,
    '/three.js/demo-2': RouteRecordInfo<'/three.js/demo-2', '/three/js/demo-2', Record<never, never>, Record<never, never>>,
    '/three.js/demo-3': RouteRecordInfo<'/three.js/demo-3', '/three/js/demo-3', Record<never, never>, Record<never, never>>,
    '/three.js/demo-4': RouteRecordInfo<'/three.js/demo-4', '/three/js/demo-4', Record<never, never>, Record<never, never>>,
  }
}
